language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
cache: pip
install:
  - pip install --process-dependency-links .[xanthos,tethys]
script:
  - python -m unittest
