language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
cache: pip
install:
  - pip install git+https://github.com/JGCRI/gcam_reader
  - pip install git+https://github.com/JGCRI/tethys
  - pip install git+https://github.com/JGCRI/xanthos
  - pip install .
script:
  - python -m unittest
