language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7

before_install:
  - |
    sudo apt-get install -y lsb-release
      sudo apt-key adv \
        --keyserver keyserver.ubuntu.com \
        --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
      sudo add-apt-repository \
        --yes \
        "deb https://cloud.r-project.org/bin/linux/ubuntu/ $(lsb_release -c -s)-cran36/"
      cat /etc/apt/sources.list
      sudo apt-get update -qq
      sudo apt-get install -y r-base
  - sudo Rscript ./install_r_packages.r dplyr ggplot2 tidyr

cache: pip

install:
  - pip install git+https://github.com/JGCRI/gcam_reader
  - pip install git+https://github.com/JGCRI/tethys
  - pip install git+https://github.com/JGCRI/xanthos
  - pip install .

script:
  - python -m unittest
